import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Saidbar from "./ui/Saidbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <div className='flex bg-gray-900'>
     <div className=" flex-1 sticky top-0 h-[100vh]">
           <Saidbar/> 
        </div>
       <div className=' flex-[4_4_0%]'>
       {children}
       </div>
     </div>
  );
}
